'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { type NodeProps, Position, useNodeId } from '@xyflow/react';
import { Sparkles, Minus, Plus } from 'lucide-react';
import { TypedHandle } from '@/components/canvas/handles/TypedHandle';
import { useCanvasStore } from '@/stores/canvas-store';
import { ModelSelector, type CachedModel } from './ModelSelector';
import { DebugToggleButton, JsonDebugPanel } from './JsonDebugPanel';
import { BatchCostDialog } from './BatchCostDialog';
import { SchemaNodeRenderer } from './schema-widgets';
import { NodeFooter } from './shared/NodeFooter';
import { ImageResultGrid } from './ImageResultGrid';
import type { ImageGeneratorData } from '@/types/canvas';
import { useFalNode } from '@/hooks/use-fal-node';
import {
  humanizeFieldName,
  type ModelNodeConfig,
  type DynamicImagePort,
} from '@/lib/fal/schema-introspection';
import type { SchemaNode } from '@/lib/fal/schema-tree';
import { isImageNode, isImageArrayNode, isTextNode } from '@/lib/fal/schema-ports';
import { DynamicImageHandle, DynamicTextHandle } from './shared/DynamicHandles';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ASPECT_RATIO_PRESETS: Record<
  string,
  { width: number; height: number; label: string }
> = {
  '1:1': { width: 1024, height: 1024, label: '1:1' },
  '3:4': { width: 768, height: 1024, label: '3:4' },
  '4:3': { width: 1024, height: 768, label: '4:3' },
  '9:16': { width: 576, height: 1024, label: '9:16' },
  '16:9': { width: 1024, height: 576, label: '16:9' },
};

const DEFAULT_MODEL = 'fal-ai/flux/dev';

const DEFAULT_IMAGE_CONFIG: ModelNodeConfig = {
  hasPrompt: true,
  hasImageUrl: true,
  hasLastFrame: false,
  hasSeed: true,
  hasDuration: false,
  hasAspectRatio: false,
  hasNumImages: true,
  hasGuidanceScale: false,
  hasNegativePrompt: false,
  hasImageSize: true,
};

const IMAGE_SIZE_LABELS: Record<string, string> = {
  'square_hd': '1:1 HD',
  'square': '1:1',
  'portrait_4_3': '3:4',
  'portrait_16_9': '9:16',
  'landscape_4_3': '4:3',
  'landscape_16_9': '16:9',
};

// ---------------------------------------------------------------------------
// Shimmer loading animation component
// ---------------------------------------------------------------------------

function ShimmerPlaceholder({ aspectRatio }: { aspectRatio: string }) {
  const preset = ASPECT_RATIO_PRESETS[aspectRatio] ?? ASPECT_RATIO_PRESETS['1:1'];
  return (
    <div
      className="shimmer-loading w-full overflow-hidden rounded-md"
      style={{ aspectRatio: `${preset.width}/${preset.height}` }}
    />
  );
}

// ---------------------------------------------------------------------------
// ImageGeneratorNode
// ---------------------------------------------------------------------------

export function ImageGeneratorNode({ id, data, selected }: NodeProps) {
  const nodeId = useNodeId() ?? id;
  const nodeData = data as unknown as ImageGeneratorData;

  const {
    execState,
    isRunning,
    hasError,
    handleRun,
    config,
    schemaFields,
    dynamicImagePorts,
    schemaTree,
    paramValues,
    setParam,
    filteredTree,
    debugMode,
    setDebugMode,
    costDialogOpen,
    setCostDialogOpen,
    handleCostConfirm,
    model,
    statusBorder,
    costTooltip,
    textInputConnected,
    updateData,
    updateNodeData,
    handleModelChange,
    upstreamBatch,
    isBatchConnected,
    edges,
  } = useFalNode({
    nodeId,
    nodeData: data as unknown as Record<string, unknown>,
    defaultModel: DEFAULT_MODEL,
    defaultConfig: DEFAULT_IMAGE_CONFIG,
    hasDynamicPorts: true,
    hasQueueStatus: false,
  });

  const [selectedModelInfo, setSelectedModelInfo] = useState<CachedModel | null>(null);

  // Stale edge cleanup on mount (migration from pre-Phase-32 hardcoded handle IDs)
  const deleteEdge = useCanvasStore((s) => s.deleteEdge);
  const migratedRef = useRef(false);
  useEffect(() => {
    if (migratedRef.current) return;
    migratedRef.current = true;
    // Only clean up truly obsolete handle IDs. Note: 'text-target-0' is the
    // ACTIVE prompt handle ID (generated by TypedHandle), so do NOT remove it.
    for (const oldStaticId of ['image-target-1']) {
      const staleEdge = edges.find(
        (e) => e.target === nodeId && e.targetHandle === oldStaticId,
      );
      if (staleEdge) {
        deleteEdge(staleEdge.id);
      }
    }
  }, [edges, nodeId, deleteEdge]);

  // Build port lookup map for renderImagePort callback
  const portMap = useMemo(() => {
    const map = new Map<string, DynamicImagePort>();
    for (const port of dynamicImagePorts) {
      map.set(port.fieldName, port);
    }
    return map;
  }, [dynamicImagePorts]);

  const renderImagePort = useCallback((node: SchemaNode) => {
    const port = portMap.get(node.path);
    if (port) {
      const handleId = `image-target-${port.fieldName}`;
      return <DynamicImageHandle port={port} handleId={handleId} />;
    }

    const isImg = isImageNode(node);
    const isImgArr = isImageArrayNode(node);
    if (!isImg && !isImgArr) return null;

    const dynPort: DynamicImagePort = {
      fieldName: node.path,
      label: humanizeFieldName(node.name),
      required: node.required,
      description: node.description,
      multi: isImgArr,
      maxConnections: isImgArr ? node.maxItems : 1,
    };
    const handleId = `image-target-${node.path}`;
    return <DynamicImageHandle port={dynPort} handleId={handleId} />;
  }, [portMap]);

  const renderTextPort = useCallback((node: SchemaNode) => {
    if (!isTextNode(node)) return null;
    const handleId = `text-target-${node.path}`;
    const val = paramValues[node.path] as string | undefined;
    return (
      <DynamicTextHandle
        node={node}
        handleId={handleId}
        value={val}
        onChange={(v) => setParam(node.path, v)}
      />
    );
  }, [paramValues, setParam]);

  const handleSelectImage = useCallback(
    (index: number) => {
      updateNodeData(nodeId, { selectedImageIndex: index });
    },
    [nodeId, updateNodeData],
  );

  const category: 'text-to-image' | 'image-to-image' = nodeData.mode === 'image-to-image' ? 'image-to-image' : 'text-to-image';
  const aspectRatio = nodeData.aspectRatio ?? '1:1';
  const numImages = nodeData.numImages ?? 1;
  const images = nodeData.images ?? [];
  const selectedImageIndex = nodeData.selectedImageIndex ?? 0;

  return (
    <div
      className={`group relative rounded-lg border-2 bg-[#1a1a1a] shadow-lg transition-all ${statusBorder} ${
        selected ? 'ring-2 ring-[#ae53ba] ring-offset-1 ring-offset-transparent' : ''
      }`}
      style={{ minWidth: 320, maxWidth: 400 }}
    >
      {/* Output handle */}
      <TypedHandle
        type="source"
        position={Position.Right}
        portType="image"
        portId="image-out-0"
        index={0}
        style={{ top: '50%' }}
      />

      {/* Header */}
      <div className="flex items-center gap-2 border-b border-white/5 px-3 py-2">
        <Sparkles className="h-4 w-4 text-purple-400" />
        <span className="text-xs font-semibold text-gray-100">
          Image Generator
        </span>
      </div>

      {/* Result area */}
      <div className="relative px-3 py-2">
        <DebugToggleButton active={debugMode} onClick={() => setDebugMode((v) => !v)} />
        {debugMode ? (
          <JsonDebugPanel
            schema={schemaFields}
            schemaTree={schemaTree}
            config={{ model, prompt: nodeData.prompt, aspectRatio, numImages, imageSizeOption: (nodeData as Record<string, unknown>).imageSizeOption }}
            request={nodeData.debugRequest}
            response={nodeData.debugResponse}
            error={nodeData.debugError}
          />
        ) : (
          <>
            {isRunning && <ShimmerPlaceholder aspectRatio={aspectRatio} />}
            {hasError && execState?.error && (
              <div className="rounded-md border border-red-500/30 bg-red-900/20 p-3 text-xs text-red-400">
                {execState.error}
              </div>
            )}
            {!isRunning && images.length > 0 && (
              <ImageResultGrid
                images={images}
                selectedImageIndex={selectedImageIndex}
                onSelectImage={handleSelectImage}
              />
            )}
            {!isRunning && images.length === 0 && !hasError && (
              <ShimmerPlaceholder aspectRatio={aspectRatio} />
            )}
          </>
        )}
      </div>

      {/* Controls */}
      <div className="border-t border-white/5 px-3 py-2">
        {/* Category toggle */}
        <div className="mb-2">
          <label className="mb-1 block text-[10px] font-medium uppercase tracking-wider text-gray-500">
            Category
          </label>
          <div className="flex gap-0.5">
            {(['text-to-image', 'image-to-image'] as const).map((m) => (
              <button
                key={m}
                className={`nodrag rounded px-1.5 py-0.5 text-[10px] transition-colors ${
                  category === m
                    ? 'bg-purple-500/20 text-purple-300'
                    : 'bg-white/5 text-gray-500 hover:bg-white/10 hover:text-gray-300'
                }`}
                onClick={() => {
                  if (m === category) return;
                  updateData('mode', m);
                  updateData('model', m === 'text-to-image' ? 'fal-ai/flux/dev' : '');
                }}
              >
                {m === 'text-to-image' ? 'Text to Image' : 'Image to Image'}
              </button>
            ))}
          </div>
        </div>

        <div className="mb-2">
          <label className="mb-1 block text-[10px] font-medium uppercase tracking-wider text-gray-500">
            Model
          </label>
          <ModelSelector
            value={model}
            onChange={handleModelChange}
            mode={category}
            onPricingInfo={(info) => updateNodeData(nodeId, { unitPrice: info.unitPrice, priceUnit: info.priceUnit })}
            onModelInfo={setSelectedModelInfo}
          />
        </div>

        {/* Aspect ratio + count */}
        <div className="flex items-end gap-2">
          <div className="flex-1">
            <label className="mb-1 block text-[10px] font-medium uppercase tracking-wider text-gray-500">
              Aspect
            </label>
            <div className="flex flex-wrap gap-0.5">
              {config.hasAspectRatio && config.aspectRatioOptions && config.aspectRatioOptions.length > 0 ? (
                config.aspectRatioOptions.map((option) => (
                  <button
                    key={option}
                    className={`nodrag rounded px-1.5 py-0.5 text-[10px] transition-colors ${
                      (paramValues.aspect_ratio ?? config.aspectRatioOptions![0]) === option
                        ? 'bg-purple-500/20 text-purple-300'
                        : 'bg-white/5 text-gray-500 hover:bg-white/10 hover:text-gray-300'
                    }`}
                    onClick={() => setParam('aspect_ratio', option)}
                    title={option}
                  >
                    {option}
                  </button>
                ))
              ) : config.hasImageSize && config.imageSizeOptions && config.imageSizeOptions.length > 0 ? (
                config.imageSizeOptions.map((option) => (
                  <button
                    key={option}
                    className={`nodrag rounded px-1.5 py-0.5 text-[10px] transition-colors ${
                      nodeData.imageSizeOption === option
                        ? 'bg-purple-500/20 text-purple-300'
                        : 'bg-white/5 text-gray-500 hover:bg-white/10 hover:text-gray-300'
                    }`}
                    onClick={() => {
                      updateData('imageSizeOption', option);
                      updateData('aspectRatio', IMAGE_SIZE_LABELS[option] ?? option);
                    }}
                    title={option}
                  >
                    {IMAGE_SIZE_LABELS[option] ?? option}
                  </button>
                ))
              ) : (
                Object.entries(ASPECT_RATIO_PRESETS).map(([key, preset]) => (
                  <button
                    key={key}
                    className={`nodrag rounded px-1.5 py-0.5 text-[10px] transition-colors ${
                      aspectRatio === key
                        ? 'bg-purple-500/20 text-purple-300'
                        : 'bg-white/5 text-gray-500 hover:bg-white/10 hover:text-gray-300'
                    }`}
                    onClick={() => {
                      updateData('aspectRatio', key);
                      updateData('imageSizeOption', undefined);
                    }}
                    title={`${preset.width}x${preset.height}`}
                  >
                    {preset.label}
                  </button>
                ))
              )}
            </div>
          </div>

          {config.hasNumImages && (
            <div className={isBatchConnected ? 'opacity-40' : ''}>
              <label className="mb-1 block text-[10px] font-medium uppercase tracking-wider text-gray-500">
                Count{isBatchConnected ? ' (batch)' : ''}
              </label>
              <div className="flex items-center gap-1">
                <button
                  className="nodrag rounded bg-white/5 p-0.5 text-gray-400 transition-colors hover:bg-white/10 hover:text-gray-200 disabled:cursor-not-allowed disabled:opacity-30"
                  onClick={() =>
                    updateData('numImages', Math.max(1, numImages - 1))
                  }
                  disabled={numImages <= 1 || isBatchConnected}
                >
                  <Minus className="h-3 w-3" />
                </button>
                <span className="w-5 text-center text-xs text-gray-300">
                  {isBatchConnected ? 1 : numImages}
                </span>
                <button
                  className="nodrag rounded bg-white/5 p-0.5 text-gray-400 transition-colors hover:bg-white/10 hover:text-gray-200 disabled:cursor-not-allowed disabled:opacity-30"
                  onClick={() =>
                    updateData('numImages', Math.min(4, numImages + 1))
                  }
                  disabled={numImages >= 4 || isBatchConnected}
                >
                  <Plus className="h-3 w-3" />
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Dynamic schema fields (image ports, text ports, other params) */}
        {filteredTree.length > 0 ? (
          <div className="mb-2 space-y-1">
            {filteredTree.map((node) => (
              <SchemaNodeRenderer
                key={node.path}
                node={node}
                values={paramValues}
                onChange={setParam}
                renderImagePort={renderImagePort}
                renderTextPort={renderTextPort}
              />
            ))}
          </div>
        ) : null}

        {/* Dedicated prompt section (outside filteredTree, like I2V) */}
        {config.hasPrompt && (
          <div className="relative">
            <TypedHandle
              type="target"
              position={Position.Left}
              portType="text"
              portId="text-in-0"
              index={0}
              style={{ left: 0 }}
            />
            <label className="mb-1 block text-[10px] font-medium uppercase tracking-wider text-gray-500">
              Prompt
            </label>
            {textInputConnected ? (
              <div className="rounded-md border border-white/5 bg-white/[0.02] px-3 py-2 text-xs text-gray-500">
                Prompt from connected node
              </div>
            ) : (
              <textarea
                className="nodrag nowheel w-full resize-none rounded-md border border-white/10 bg-white/5 px-3 py-2 text-xs text-gray-200 outline-none transition-colors placeholder:text-gray-600 focus:border-white/20"
                placeholder="Describe the image you want to generate..."
                rows={3}
                value={nodeData.prompt ?? ''}
                onChange={(e) => updateData('prompt', e.target.value)}
              />
            )}
          </div>
        )}
      </div>

      {/* Batch cost dialog */}
      <BatchCostDialog
        open={costDialogOpen}
        onConfirm={handleCostConfirm}
        onCancel={() => setCostDialogOpen(false)}
        itemCount={upstreamBatch?.values.length ?? 0}
        unitPrice={(nodeData as Record<string, unknown>).unitPrice as number | null ?? null}
        priceUnit={(nodeData as Record<string, unknown>).priceUnit as string | null ?? null}
        modelName={model}
      />

      {/* Model info + Run button */}
      <NodeFooter
        modelInfo={selectedModelInfo}
        isRunning={isRunning}
        onRun={handleRun}
        costTooltip={costTooltip}
      />

    </div>
  );
}
